#!/usr/bin/env python3
"""Render every tool-specific agent file from the shared source in `agents/`.

    python agents/sync.py            # write the generated files
    python agents/sync.py --check    # exit 1 if anything is stale (use in CI)

No third-party packages: uses stdlib `tomllib` (Python 3.11+).

Why a generator instead of just imports?
----------------------------------------
Import support is inconsistent across tools:

  * Claude Code resolves `@path` imports in CLAUDE.md.
  * Gemini CLI resolves `@file.md` imports in GEMINI.md.
  * Codex reads AGENTS.md as plain markdown — no import syntax.

So AGENTS.md has to be self-contained, while CLAUDE.md and GEMINI.md stay thin
and import it. Rendering everything from one source is the only way to get both
without maintaining the same instructions three times.

Edit `agents/coordinator.md`, `agents/roles/*.md`, `agents/roles.toml` or
`agents/vendor/*.md` — never the generated files.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    sys.exit("Python 3.11+ required (stdlib tomllib), or: pip install tomli")

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

BANNER = (
    "<!-- GENERATED by agents/sync.py — do not edit.\n"
    "     Edit agents/coordinator.md, agents/roles/*.md, agents/roles.toml,\n"
    "     or agents/vendor/*.md, then run: python agents/sync.py -->\n"
)


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8").strip()


def demote(md: str, levels: int = 1) -> str:
    """Add `levels` to every markdown heading, skipping fenced code blocks.

    Lets coordinator.md keep its own `#` title while embedding cleanly under
    AGENTS.md's `#`. Code fences are skipped so `# comments` in shell blocks are
    left alone.
    """
    out, in_fence = [], False
    for line in md.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
        if not in_fence and stripped.startswith("#"):
            out.append("#" * levels + line)
        else:
            out.append(line)
    return "\n".join(out)


def load_meta() -> dict:
    return tomllib.loads((HERE / "roles.toml").read_text(encoding="utf-8"))


def load_policy() -> dict:
    return tomllib.loads((HERE / "policy.toml").read_text(encoding="utf-8"))


def one_line(text: str) -> str:
    return " ".join(text.split())


def role_table(meta: dict) -> str:
    rows = ["| Role | For | Delegate when… |", "|---|---|---|"]
    for name in meta["order"]:
        r = meta["roles"][name]
        rows.append(f"| `{name}` | {r['summary']} | {r['when']} |")
    return "\n".join(rows)


# --------------------------------------------------------------------------
# AGENTS.md — the canonical, self-contained file.
# Read by Codex, Mistral Vibe, and 20+ other agents (open format, AAIF).
# --------------------------------------------------------------------------
def render_agents_md(meta: dict) -> str:
    parts = [
        BANNER,
        "# AGENTS.md",
        "",
        "Instructions for AI coding agents working in this repo. This is the "
        "**canonical, model-agnostic** file: `CLAUDE.md` and `GEMINI.md` import "
        "it rather than duplicating it.",
        "",
        demote(read(HERE / "coordinator.md")),
        "",
        "## Sub-agent roles",
        "",
        role_table(meta),
        "",
        "The full prompt for each role lives in `agents/roles/<name>.md`. Read it "
        "**when you take on that role**, not before — keeping the prompts out of "
        "this always-loaded file is what keeps the context budget small. Tools "
        "with native sub-agents already have their own copy "
        "(`.claude/agents/`, `.vibe/agents/`) and load it on delegation.",
        "",
    ]
    return "\n".join(parts).rstrip() + "\n"


# --------------------------------------------------------------------------
# CLAUDE.md / GEMINI.md — thin, import the canonical file.
# --------------------------------------------------------------------------
def render_claude_md() -> str:
    return "\n".join([
        BANNER,
        "# CLAUDE.md",
        "",
        "The shared coordinator instructions and role definitions live in "
        "`AGENTS.md` and are imported here:",
        "",
        "@AGENTS.md",
        "",
        read(HERE / "vendor" / "claude.md"),
        "",
    ]).rstrip() + "\n"


def render_gemini_md() -> str:
    return "\n".join([
        BANNER,
        "# GEMINI.md",
        "",
        "The shared coordinator instructions live in `AGENTS.md` and are "
        "imported here:",
        "",
        "@./AGENTS.md",
        "",
        read(HERE / "vendor" / "gemini.md"),
        "",
    ]).rstrip() + "\n"


# --------------------------------------------------------------------------
# Claude Code native sub-agents: .claude/agents/<role>.md
# --------------------------------------------------------------------------
def render_claude_subagent(name: str, r: dict) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {one_line(r['description'])}\n"
        f"tools: {', '.join(r['claude']['tools'])}\n"
        f"model: {r['claude']['model']}\n"
        "---\n"
        f"<!-- GENERATED by agents/sync.py — edit agents/roles/{name}.md instead. -->\n\n"
        f"{read(HERE / 'roles' / f'{name}.md')}\n"
    )


# --------------------------------------------------------------------------
# Mistral Vibe sub-agents: .vibe/agents/<role>.toml
# Vibe reads AGENTS.md automatically; this only adds delegable sub-agents.
# Schema beyond agent_type/description is best-effort — verify against the
# current Mistral Vibe docs, which document the prompt directory at user level.
# --------------------------------------------------------------------------
def render_vibe_agent(name: str, r: dict) -> str:
    tools = ", ".join(f'"{t}"' for t in r["vibe"]["enabled_tools"])
    desc = one_line(r["description"]).replace('"', "'")
    return (
        f"# GENERATED by agents/sync.py — edit agents/roles/{name}.md instead.\n"
        "# Verify field names against the current Mistral Vibe docs.\n"
        'agent_type = "subagent"\n'
        f'description = "{desc}"\n'
        f"enabled_tools = [{tools}]\n"
        f'system_prompt_id = "{name}"\n'
    )


# --------------------------------------------------------------------------
# Enforcement layer. AGENTS.md is context (lowers the *probability* of an
# accident); these lower the *possibility*. A PreToolUse hook runs before the
# permission check and blocks even in bypass mode; a hook can tighten policy but
# never loosen a `deny` rule.
# Verify the settings schema against the current Claude Code docs — it evolves.
# --------------------------------------------------------------------------
def render_claude_settings(policy: dict) -> str:
    """Sandbox + permission rules + hook registration.

    Schema mirrors Anthropic's own example at
    anthropics/claude-code/examples/settings/settings-bash-sandbox.json.
    """
    perms = policy.get("permissions", {})
    sb = policy.get("sandbox", {})
    settings = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        # 1. The boundary. Holds even when a prompt injection bypasses the model.
        "sandbox": {
            "enabled": sb.get("enabled", True),
            "autoAllowBashIfSandboxed": sb.get("autoAllowBashIfSandboxed", False),
            "allowUnsandboxedCommands": sb.get("allowUnsandboxedCommands", False),
            "excludedCommands": sb.get("excludedCommands", []),
            "enableWeakerNestedSandbox": sb.get("enableWeakerNestedSandbox", False),
            "network": sb.get("network", {}),
            "filesystem": sb.get("filesystem", {}),
        },
        # 2. Declarative rules. Deny beats allow at every scope.
        "permissions": {
            "deny": perms.get("deny", []),
            "ask": perms.get("ask", []),
            "allow": perms.get("allow", []),
        },
        # 3. Only what the layers above cannot express.
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": "python3 .claude/hooks/guard.py"}],
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "*",
                    "hooks": [{"type": "command", "command": "python3 .claude/hooks/trace.py"}],
                }
            ],
        },
    }
    return json.dumps(settings, indent=2) + "\n"


def render_policy_json(policy: dict) -> str:
    """Machine-readable policy read by guard.py at runtime."""
    return json.dumps(policy, indent=2) + "\n"


def render_managed_settings() -> str:
    """Org-level lockdown. Lives OUTSIDE the repo (a system path requiring admin
    rights), so this is a reference copy, not something a project can self-apply.
    A deny in managed settings cannot be overridden by any lower scope."""
    return json.dumps(
        {
            "_comment": "Deploy to the managed-settings path for your OS. Not read from a repo.",
            "permissions": {"disableBypassPermissionsMode": "disable"},
            "allowManagedPermissionRulesOnly": True,
            "allowManagedHooksOnly": True,
            "sandbox": {"enabled": True, "allowUnsandboxedCommands": False},
        },
        indent=2,
    ) + "\n"


def render_geminiignore() -> str:
    return (
        "# GENERATED by agents/sync.py — edit agents/policy.toml instead.\n"
        "# Keeps secrets and noise out of the agent's view. NOTE: ignore files\n"
        "# are advisory — only the PreToolUse hook reliably blocks access.\n"
        ".env\n.env.*\nsecrets/\n*.pem\n*.key\nid_rsa\nid_ed25519\n"
        ".agent/\nnode_modules/\n__pycache__/\n"
    )


# --------------------------------------------------------------------------
def build(meta: dict) -> dict[Path, str]:
    policy = load_policy()
    out: dict[Path, str] = {
        ROOT / "AGENTS.md": render_agents_md(meta),
        ROOT / "CLAUDE.md": render_claude_md(),
        ROOT / "GEMINI.md": render_gemini_md(),
        # enforcement layer
        ROOT / ".claude" / "settings.json": render_claude_settings(policy),
        ROOT / ".claude" / "hooks" / "policy.json": render_policy_json(policy),
        ROOT / ".claude" / "hooks" / "guard.py": read(HERE / "hooks" / "guard.py") + "\n",
        ROOT / ".claude" / "hooks" / "trace.py": read(HERE / "hooks" / "trace.py") + "\n",
        ROOT / ".geminiignore": render_geminiignore(),
        ROOT / "managed-settings.example.json": render_managed_settings(),
    }
    for name in meta["order"]:
        r = meta["roles"][name]
        out[ROOT / ".claude" / "agents" / f"{name}.md"] = render_claude_subagent(name, r)
        out[ROOT / ".vibe" / "agents" / f"{name}.toml"] = render_vibe_agent(name, r)
        out[ROOT / ".vibe" / "prompts" / f"{name}.md"] = read(HERE / "roles" / f"{name}.md") + "\n"
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Render agent files from agents/.")
    ap.add_argument("--check", action="store_true", help="fail if files are stale")
    args = ap.parse_args()

    files = build(load_meta())

    if args.check:
        stale = [
            p for p, content in files.items()
            if not p.exists() or p.read_text(encoding="utf-8") != content
        ]
        for p in stale:
            print(f"STALE: {p.relative_to(ROOT)}")
        if stale:
            print(f"\n{len(stale)} file(s) out of date. Run: python agents/sync.py")
            return 1
        print(f"All {len(files)} generated file(s) up to date.")
        return 0

    for p, content in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        # Hooks are invoked as scripts; make them executable.
        if p.suffix == ".py" and p.parent.name == "hooks":
            os.chmod(p, 0o755)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
